### ISSUE TITLE
Neutron supports transparency?

### ISSUE THREAD

**Issue by adrian88888888** [G33kDude/Neutron.ahk#25]
For example if I want to display a circle, can I make the rest(the corners) transparent?
Thanks!

**Comment by SaifAqqad** [comment]
You can use [WinSet, TransColor](https://www.autohotkey.com/docs/commands/WinSet.htm#TransColor)

Just set the background-color to something specific like `#00ff00` and then:
```ahk
 WinSet​, ​TransColor​, ​ 00ff00, % ​"​ahk_id ​"​ neutron.hWnd
```

**Comment by adrian88888888** [comment]
It does not get fully transparent:
![image](https://user-images.githubusercontent.com/63675374/160932858-c702980c-5939-4c6b-a2c3-4afc06509128.png)
The code:
```AutoHotKey
WinSet, TransColor, 444444, ahk_class AutoHotkeyGUI
```
Also there is anti-aliasing on the edges of the numbers...I imagined this would happen :(
there's other workarounds?, no one had this problem in neutron?

**Comment by adrian88888888** [comment]
I couldn't find anything in google :(, but many thanks bro because it's 10 times better than nothing
You can close this thread

**Comment by aghster** [comment]
> there's other workarounds?

@adrian88888888
Possibly the blur effect is due to Neutron.ahk enabling the "blurbehind" accent policy to avoid some resizing artifacts. If you don't care about these artifacts, you may prevent this by commenting out [line 292](https://github.com/G33kDude/Neutron.ahk/blob/a1ec4de705b1cc6d73519169d15545b0fe5f3600/Neutron.ahk#L292) in your local copy of Neutron.ahk by placing a semicolon at the beginning of the line:

`		; DllCall("SetWindowCompositionAttribute", "UPtr", hWnd, "UPtr", &wcad)`

**Comment by adrian88888888** [comment]
@aghster Thank you!!!! that's better
