### ISSUE TITLE
browser version

### ISSUE THREAD

**Issue by huo-feng-ding** [G33kDude/Neutron.ahk#34]
in html I use `alert(window.navigator.userAgent)`  show 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19045
```

but in edge browser  show
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.76
```

Neutron browser version is too old, some script grammar like `()=>{console.log('test')}` is error

**Comment by G33kDude** [comment]
Neutron is a wrapper for the Trident engine, used by Internet Explorer, on which development was stopped by Microsoft years ago. Nothing you or I can do will make Microsoft resume development of Internet Explorer.

If you'd like to use newer features in Trident, you can use Babel to convert your new JS into old JS.

If you'd like to use a new engine, you should consider using WebView2 instead of Neutron like thqby demonstrates here https://www.autohotkey.com/boards/viewtopic.php?t=95666

**Comment by huo-feng-ding** [comment]
thank you!
