### ISSUE TITLE
WebView2 Conversion / Trident end of life 2029

### ISSUE THREAD

**Issue by cpdx4** [G33kDude/Neutron.ahk#39]
As of this post, the legacy WebView (Trident) engine is [5 years away from being discontinued](https://techcommunity.microsoft.com/t5/access-blog/ie-11-retirement-what-does-this-mean-for-microsoft-access-apps/ba-p/3261899) by Microsoft.

Conversion to WebView2 would seem the next logical step, but would require significant rework.

**Comment by The-CoDingman** [comment]
> As of this post, the legacy WebView (Trident) engine is [5 years away from being discontinued](https://techcommunity.microsoft.com/t5/access-blog/ie-11-retirement-what-does-this-mean-for-microsoft-access-apps/ba-p/3261899) by Microsoft.
> 
> Conversion to WebView2 would seem the next logical step, but would require significant rework.

Thqby has written a WebView2 library that allows one to use a WebView2 instance inside of an AHK GUI.  Their library is a little higher level than the Neutron library, because of this I've been working on a Library that extends Thqby's and aims to provide as close as possible to the same experience of using the Neutron Library.

https://github.com/thqby/ahk2_lib/tree/master/WebView2
https://github.com/The-CoDingman/WebViewToo

**Comment by cpdx4** [comment]
Thanks so much! I gave it a try and **WebViewToo** worked pretty well. What an exciting iteration. Thank you for the work you've done to make this a reality.
